
swa_start: 3
n_epochs: 100
losse: mse
model_params:
  n_layers: 5
  lr: 1e-3
  batch_size: 64

some_list: [1,2,3,4]  # this is just some list
something:

is_train: True | true | yes --> bool
